In [1]:
#Dependencies

import requests
import json
from matplotlib import pyplot as plt
from scipy import stats
from scipy.stats import linregress
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# The path to our CSV file
#(name the file we are going to read as "file_gdp")
file_gdp = "suicides_vs_gdp_o.csv"

# Read Suicide Data our Kickstarter data into pandas 
#rename it as a dataframe(df) for ease of readibiity
su_vs_gdp_o_df = pd.read_csv(file_gdp)

# Display all columns 
# su_vs_gdp_o_df.columns

# # Display information of the df
# su_vs_gdp_o_df.info()

In [5]:
# Group using 'country-year' column and using the aggregate command to define/combine data to respective column.
# for ease of readibility(also we are ommitting columns we do not need)
su_vs_gdp_df = su_vs_gdp_o_df.groupby('country-year').agg({'country':'first', 'year':'first', 
                                                           'suicides_no':'sum','population':'sum', 
                                                           'suicides/100k pop':'sum',
                                                           'year_gdp':'first',
                                                           'gdp_per_capita':'first'}).reset_index()
# Save/Create CSV file
su_vs_gdp_df.to_csv('cleaned_su_vs_gdp.csv')

In [6]:
# Read/Create new df(all years, all suicide rates)
clean = "cleaned_su_vs_gdp.csv"

su_vs_gdp_c_df = pd.read_csv(clean)
su_vs_gdp_c_df

,Unnamed: 0,country-year,country,year,suicides_no,population,suicides/100k pop,year_gdp,gdp_per_capita
0,0,Albania1987,Albania,1987,73,2709600,31.85,2.160000e+09,$796.00
1,1,Albania1988,Albania,1988,63,2764300,32.46,2.130000e+09,$769.00
2,2,Albania1989,Albania,1989,68,2803100,33.40,2.340000e+09,$833.00
3,3,Albania1992,Albania,1992,47,2822500,18.00,7.090000e+08,$251.00
4,4,Albania1993,Albania,1993,73,2807300,32.56,1.230000e+09,$437.00
5,5,Albania1994,Albania,1994,50,2849300,32.18,1.990000e+09,$697.00
6,6,Albania1995,Albania,1995,88,2903400,40.55,2.420000e+09,$835.00
7,7,Albania1996,Albania,1996,89,2940200,43.62,3.310000e+09,"$1,127.00"
8,8,Albania1997,Albania,1997,170,2977300,77.43,2.360000e+09,$793.00
9,9,Albania1998,Albania,1998,154,3012700,66.52,2.710000e+09,$899.00
10,10,Albania1999,Albania,1999,139,3029700,69.81,3.410000e+09,"$1,127.00"
11,11,Albania2000,Albania,2000,54,2796300,30.70,3.630000e+09,"$1,299.00"
12,12,Albania2001,Albania,2001,119,2799349,50.62,4.060000e+09,"$1,451.00"
13,13,Albania2002,Albania,2002,133,2818839,62.51,4.440000e+09,"$1,573.00"
14,14,Albania2003,Albania,2003,124,2843929,58.60,5.750000e+09,"$2,021.00"
15,15,Albania2004,Albania,2004,146,2874991,65.39,7.310000e+09,"$2,544.00"
16,16,Albania2005,Albania,2005,0,2783320,0.00,8.160000e+09,"$2,931.00"
17,17,Albania2006,Albania,2006,0,2780176,0.00,8.990000e+09,"$3,235.00"
18,18,Albania2007,Albania,2007,124,2770344,65.85,1.070000e+10,"$3,863.00"
19,19,Albania2008,Albania,2008,160,2757059,71.05,1.290000e+10,"$4,672.00"
20,20,Albania2009,Albania,2009,0,2745735,0.00,1.200000e+10,"$4,387.00"
21,21,Albania2010,Albania,2010,96,2736025,41.66,1.190000e+10,"$4,359.00"
22,22,Antigua and Barbuda1985,Antigua and Barbuda,1985,0,62574,0.00,2.410000e+08,"$3,850.00"
23,23,Antigua and Barbuda1986,Antigua and Barbuda,1986,0,61270,0.00,2.900000e+08,"$4,740.00"
24,24,Antigua and Barbuda1987,Antigua and Barbuda,1987,0,60261,0.00,3.370000e+08,"$5,595.00"
25,25,Antigua and Barbuda1988,Antigua and Barbuda,1988,0,59564,0.00,3.990000e+08,"$6,693.00"
26,26,Antigua and Barbuda1989,Antigua and Barbuda,1989,0,59238,0.00,4.390000e+08,"$7,407.00"
27,27,Antigua and Barbuda1990,Antigua and Barbuda,1990,1,59334,17.24,4.590000e+08,"$7,744.00"
28,28,Antigua and Barbuda1991,Antigua and Barbuda,1991,0,60394,0.00,4.820000e+08,"$7,976.00"
29,29,Antigua and Barbuda1992,Antigua and Barbuda,1992,0,61741,0.00,4.990000e+08,"$8,087.00"
...,...,...,...,...,...,...,...,...,...
2291,2291,Uruguay2007,Uruguay,2007,576,3087957,266.31,2.340000e+10,"$7,581.00"
2292,2292,Uruguay2008,Uruguay,2008,523,3100791,234.53,3.040000e+10,"$9,793.00"
2293,2293,Uruguay2009,Uruguay,2009,511,3114306,237.75,3.170000e+10,"$10,166.00"
2294,2294,Uruguay2010,Uruguay,2010,547,3127306,257.43,4.030000e+10,"$12,882.00"
2295,2295,Uruguay2012,Uruguay,2012,599,3151939,264.35,5.130000e+10,"$16,264.00"
2296,2296,Uruguay2013,Uruguay,2013,546,3164670,249.09,5.750000e+10,"$18,179.00"
2297,2297,Uruguay2014,Uruguay,2014,591,3177645,248.64,5.720000e+10,"$18,012.00"
2298,2298,Uruguay2015,Uruguay,2015,630,3190795,270.02,5.330000e+10,"$16,696.00"
2299,2299,Uzbekistan1990,Uzbekistan,1990,1459,17165700,129.36,1.340000e+10,$778.00
2300,2300,Uzbekistan1991,Uzbekistan,1991,1393,17347800,124.18,1.370000e+10,$788.00
2301,2301,Uzbekistan1992,Uzbekistan,1992,1344,18257000,111.29,1.290000e+10,$709.00
2302,2302,Uzbekistan1993,Uzbekistan,1993,1355,18509300,111.76,1.310000e+10,$708.00
2303,2303,Uzbekistan1994,Uzbekistan,1994,1419,19144700,110.85,1.290000e+10,$674.00
2304,2304,Uzbekistan1995,Uzbekistan,1995,1485,19599000,111.30,1.340000e+10,$681.00
2305,2305,Uzbekistan1996,Uzbekistan,1996,1699,19854500,125.06,1.390000e+10,$703.00
2306,2306,Uzbekistan1997,Uzbekistan,1997,1554,20364300,110.58,1.470000e+10,$724.00
2307,2307,Uzbekistan1998,Uzbekistan,1998,1620,20861200,108.30,1.500000e+10,$719.00
2308,2308,Uzbekistan1999,Uzbekistan,1999,1795,21329916,113.33,1.710000e+10,$801.00
2309,2309,Uzbekistan2000,Uzbekistan,2000,1919,21789067,120.31,1.380000e+10,$632.00
2310,2310,Uzbekistan2001,Uzbekistan,2001,1914,22231527,115.92,1.140000e+10,$513.00
2311,2311,Uzbekistan2002,Uzbekistan,2002,1576,22632256,95.28,9.690000e+09,$428.00
2312,2312,Uzbekistan2003,Uzbekistan,2003,1416,22982883,82.06,1.010000e+10,$441.00
2313,2313,Uzbekistan2004,Uzbekistan,2004,1251,23300841,68.04,1.200000e+10,$516.00
2314,2314,Uzbekistan2005,Uzbekistan,2005,1221,23600347,67.81,1.430000e+10,$606.00
2315,2315,Uzbekistan2009,Uzbekistan,2009,1399,25288102,60.86,3.370000e+10,"$1,332.00"
2316,2316,Uzbekistan2010,Uzbekistan,2010,1464,25651783,63.23,3.930000e+10,"$1,533.00"
2317,2317,Uzbekistan2011,Uzbekistan,2011,1640,25978049,67.14,4.590000e+10,"$1,767.00"
2318,2318,Uzbekistan2012,Uzbekistan,2012,1835,26381830,77.53,5.180000e+10,"$1,964.00"
2319,2319,Uzbekistan2013,Uzbekistan,2013,1950,26838924,78.86,5.770000e+10,"$2,150.00"
2320,2320,Uzbekistan2014,Uzbekistan,2014,2095,27313507,85.12,6.310000e+10,"$2,309.00"

In [12]:
# It is possible to sort based upon multiple columns
# here we are sorting by highest gdp
sort_gdp_df = su_vs_gdp_df.sort_values(["year_gdp"], ascending=False)

# Filter the data so that only those in 2015 are in a DataFrame and save as new dataframe(df)
gdp_2015_df = sort_gdp_df.query("year == '2015'")
gdp_2015_df

#Create new dataframe(df) to hold top x countries with highest year_gdp
gdp_2015_df_top_8 = gdp_2015_df[['country','year_gdp', 'suicides/100k pop']]
gdp_2015_df_top_8

                           country      year_gdp  suicides/100k pop
2270                 United States  1.810000e+13             175.41
1145                         Japan  4.390000e+12             206.04
835                        Germany  3.380000e+12             150.34
2239                United Kingdom  2.890000e+12              86.74
1097                         Italy  1.830000e+12              78.45
378                         Brazil  1.800000e+12              77.45
1718             Republic of Korea  1.380000e+12             389.14
1773            Russian Federation  1.370000e+12             236.92
148                      Australia  1.350000e+12             154.18
1993                         Spain  1.200000e+12              97.38
1412                        Mexico  1.170000e+12              66.57
2145                        Turkey  8.600000e+11              28.47
1454                   Netherlands  7.580000e+11             126.93
2083                   Switzerland  6.790000e+11             164.66
79                       Argentina  5.950000e+11             112.13
2061                        Sweden  4.980000e+11             149.30
1614                        Poland  4.770000e+11             166.99
317                        Belgium  4.550000e+11             196.66
2110                      Thailand  4.010000e+11              81.15
1520                        Norway  3.870000e+11             136.43
179                        Austria  3.820000e+11             194.62
1962                  South Africa  3.180000e+11              13.00
1899                     Singapore  3.040000e+11             109.29
640                        Denmark  3.010000e+11             121.42
1066                        Israel  2.990000e+11              65.91
500                       Colombia  2.920000e+11              70.40
469                          Chile  2.440000e+11             147.68
757                        Finland  2.320000e+11             161.19
866                         Greece  1.960000e+11              56.06
617                 Czech Republic  1.870000e+11             170.87
...                            ...           ...                ...
1686                         Qatar  1.650000e+11              18.84
972                        Hungary  1.230000e+11             257.27
1672                   Puerto Rico  1.030000e+11              85.58
672                        Ecuador  9.930000e+10              97.39
2202                       Ukraine  9.100000e+10             244.72
576                           Cuba  8.710000e+10             194.31
922                      Guatemala  6.380000e+10              44.85
1307                    Luxembourg  5.780000e+10             134.40
1548                        Panama  5.430000e+10              44.90
2298                       Uruguay  5.330000e+10             270.02
551                        Croatia  4.940000e+10             229.68
1942                      Slovenia  4.310000e+10             264.81
1275                     Lithuania  4.150000e+10             385.48
1850                        Serbia  3.720000e+10             205.97
2174                  Turkmenistan  3.580000e+10              28.48
1254                        Latvia  2.700000e+10             251.47
717                        Estonia  2.260000e+10             205.38
590                         Cyprus  1.970000e+10              49.59
1004                       Iceland  1.690000e+10             140.65
809                        Georgia  1.400000e+10              84.68
1490                     Nicaragua  1.260000e+10              69.87
1380                     Mauritius  1.170000e+10              99.97
1349                         Malta  1.060000e+10              78.27
103                        Armenia  1.060000e+10              45.28
1233                    Kyrgyzstan  6.680000e+09              98.37
345                         Belize  1.780000e+09             135.46
1868                    Seychelles  1.380000e+09              81.25
48             Antigua and Barbuda  1.360000e+09              15.62
891                        Grenada  9.970000e+08               0.00
1829  Saint Vincent and Grenadines  7.570000e+08              28.08

[62 rows x 3 columns]